name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/continuous-delivery.yml'
  workflow_dispatch:

jobs:
  PublishDragonite:
    name: Publish diluc-bot image to container registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push dragonite Docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # tag=v2.10.0
        with:
          push: true
          context: ./
          file: Dockerfile
          tags: ghcr.io/devtomio/diluc-bot:latest

  DeployBot:
    name: Deploy the bot to Railway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: Deploy to Railway
        uses: devtomio/action-railway@b7bad8e07bcb36d2a21f90f2ee6b2510125a6948 # tag=v1.1.4
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
